name: Test

on:
  pull_request: {}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Setup Go environment
        uses: actions/setup-go@v3.0.0
        with:
          go-version: '1.17.7'
          check-latest: true
      
      - name: Run Tests
        run: go test ./...
